/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sync/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Run
         * @description Trigger an immediate ingestion run.
         */
        post: operations["sync_run_api_sync_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Status
         * @description Get per-source freshness and cache metrics.
         */
        get: operations["sync_status_api_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprints/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sprints
         * @description List sprints for a project. Returns active + completed from last 90 days.
         */
        get: operations["list_sprints_api_sprints__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/contribution-volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contribution Volume */
        get: operations["contribution_volume_api_metrics_contribution_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/velocity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Velocity */
        get: operations["velocity_api_metrics_velocity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/composition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Composition */
        get: operations["composition_api_metrics_composition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/collaboration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Collaboration */
        get: operations["collaboration_api_metrics_collaboration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/sprint-burndown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sprint Burndown */
        get: operations["sprint_burndown_api_metrics_sprint_burndown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/contribution-volume/ts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contribution Volume Ts */
        get: operations["contribution_volume_ts_api_metrics_contribution_volume_ts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/velocity/ts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Velocity Ts */
        get: operations["velocity_ts_api_metrics_velocity_ts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/collaboration/ts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Collaboration Ts */
        get: operations["collaboration_ts_api_metrics_collaboration_ts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CollaborationResponse */
        CollaborationResponse: {
            /** Review Matrix */
            review_matrix: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Per Person */
            per_person: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** CompositionResponse */
        CompositionResponse: {
            /** Issue Types */
            issue_types: {
                [key: string]: number;
            };
            /** Pr Sizes */
            pr_sizes: {
                [key: string]: number;
            };
            /** Per Source */
            per_source: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** ContributionVolumeResponse */
        ContributionVolumeResponse: {
            /** Commits */
            commits: number;
            /** Pull Requests */
            pull_requests: number;
            /** Additions */
            additions: number;
            /** Deletions */
            deletions: number;
            /** Issues Opened */
            issues_opened: number;
            /** Issues Resolved */
            issues_resolved: number;
            /** Internal Ratio */
            internal_ratio: number;
            /** External Ratio */
            external_ratio: number;
            /** Per Source */
            per_source: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SprintBurndownResponse */
        SprintBurndownResponse: {
            /** Committed */
            committed: number;
            /** Completed */
            completed: number;
            /** Carried Over */
            carried_over: number;
            /** Unit */
            unit: string;
        };
        /** SprintResponse */
        SprintResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Project */
            project: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /**
             * End Date
             * Format: date-time
             */
            end_date: string;
            /** State */
            state: string;
            /** Is Active */
            is_active: boolean;
        };
        /** SyncRunResponse */
        SyncRunResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
        };
        /** SyncStatusItem */
        SyncStatusItem: {
            /** Source */
            source: string;
            /** Last Success At */
            last_success_at: string | null;
            /** Last Status */
            last_status: string;
            /** Events Count */
            events_count: number | null;
        };
        /** SyncStatusResponse */
        SyncStatusResponse: {
            /** Sources */
            sources: components["schemas"]["SyncStatusItem"][];
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /**
             * Cache Misses
             * @default 0
             */
            cache_misses: number;
        };
        /** TimeSeriesPoint */
        TimeSeriesPoint: {
            /** Bucket */
            bucket: string;
            /** Value */
            value: {
                [key: string]: unknown;
            };
        };
        /** TimeSeriesResponse */
        TimeSeriesResponse: {
            /** Bucket Size */
            bucket_size: string;
            /** Data */
            data: components["schemas"]["TimeSeriesPoint"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VelocityResponse */
        VelocityResponse: {
            /** Cycle Time Median */
            cycle_time_median: number | null;
            /** Cycle Time P50 */
            cycle_time_p50: number | null;
            /** Cycle Time P90 */
            cycle_time_p90: number | null;
            /** Review Turnaround Median */
            review_turnaround_median: number | null;
            /** Review Turnaround P50 */
            review_turnaround_p50: number | null;
            /** Review Turnaround P90 */
            review_turnaround_p90: number | null;
            /** Per Source */
            per_source: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sync_run_api_sync_run_post: {
        parameters: {
            query?: {
                source?: string | null;
                event_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_status_api_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
        };
    };
    list_sprints_api_sprints__get: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contribution_volume_api_metrics_contribution_volume_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                sprint_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionVolumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    velocity_api_metrics_velocity_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                sprint_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VelocityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    composition_api_metrics_composition_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                sprint_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompositionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collaboration_api_metrics_collaboration_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                sprint_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollaborationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sprint_burndown_api_metrics_sprint_burndown_get: {
        parameters: {
            query: {
                sprint_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintBurndownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contribution_volume_ts_api_metrics_contribution_volume_ts_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                sprint_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    velocity_ts_api_metrics_velocity_ts_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                sprint_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collaboration_ts_api_metrics_collaboration_ts_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                sprint_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
